const cars = [
  {
    id: 1,
    brand: "BMW",
    model: "320i",
    type: "Sedan",
    year: 2012,
    price: 2150000,
    mileage: 12000,
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Black",
    horsepower: 184,
    engineSize: 1998,
    drive: "RWD",
    consumption: 6.4,
    doors: 4,
    seats: 5,
    inspection: true,
    images: [
      "../assets/images/cars/bmw1.jpg",
      "../assets/images/cars/bmw2.jpg",
      "../assets/images/cars/bmw3.jpg"
    ],
    features: ["Leather seats", "Navigation", "Bluetooth", "Rear camera"],
    description: "Modern BMW with premium interior and low mileage."
  },

  {
    id: 2,
    brand: "Mercedes",
    model: "C200",
    type: "Sedan",
    year: 2012,
    price: 2350000,
    mileage: 28000,
    fuel: "Diesel",
    transmission: "Automatic",
    color: "White",
    horsepower: 160,
    engineSize: 1950,
    drive: "RWD",
    consumption: 5.5,
    doors: 4,
    seats: 5,
    inspection: true,
    images: [
      "../assets/images/cars/merco.jpg",
      "../assets/images/cars/merco2.jpg",
      "../assets/images/cars/merco3.jpg",
      "../assets/images/cars/merco4.jpg"
    ],
    features: ["Ambient lighting", "Navigation", "Parking sensors"],
    description: "Luxury sedan with efficient diesel engine."
  },

  {
    id: 3,
    brand: "Audi",
    model: "A4",
    type: "Sedan",
    year: 2020,
    price: 1850000,
    mileage: 52000,
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Gray",
    horsepower: 150,
    engineSize: 1984,
    drive: "FWD",
    consumption: 6.2,
    doors: 4,
    seats: 5,
    inspection: true,
    images: [
      "../assets/images/cars/audi1.jpg",
      "../assets/images/cars/audi2.jpg",
      "../assets/images/cars/audi3.jpg",
      "../assets/images/cars/audi4.jpg"
    ],
    features: ["Digital cockpit", "Cruise control"],
    description: "Balanced sedan with comfort and performance."
  },

  {
    id: 4,
    brand: "Volkswagen",
    model: "Passat",
    type: "Sedan",
    year: 2020,
    price: 1450000,
    mileage: 90000,
    fuel: "Diesel",
    transmission: "Automatic",
    color: "Blue",
    horsepower: 150,
    engineSize: 1968,
    drive: "FWD",
    consumption: 5.0,
    doors: 4,
    seats: 5,
    inspection: true,
    images: [
      "../assets/images/cars/passat1.jpg",
      "../assets/images/cars/passat2.jpg",
      "../assets/images/cars/passat3.jpg"
    ],
    features: ["Apple CarPlay", "Heated seats"],
    description: "Reliable family sedan with great fuel economy."
  },

  {
    id: 5,
    brand: "BMW",
    model: "330d",
    type: "Sedan",
    year: 2013,
    price: 1300000,
    mileage: 8000,
    fuel: "Hybrid",
    transmission: "Automatic",
    color: "White",
    horsepower: 122,
    engineSize: 1798,
    drive: "FWD",
    consumption: 4.2,
    doors: 4,
    seats: 5,
    inspection: true,
    images: [
      "../assets/images/cars/bmw330d1.jpg",
      "../assets/images/cars/bmw330d2.jpg",
      "../assets/images/cars/bmw330d3.jpg"
    ],
    features: ["Lane assist", "Adaptive cruise"],
    description: "Efficient hybrid with very low consumption."
  },

  {
    id: 6,
    brand: "Honda",
    model: "Civic",
    type: "Sedan",
    year: 2021,
    price: 1350000,
    mileage: 40000,
    fuel: "Petrol",
    transmission: "Manual",
    color: "Red",
    horsepower: 182,
    engineSize: 1498,
    drive: "FWD",
    consumption: 6.8,
    doors: 4,
    seats: 5,
    inspection: true,
    images: [
      "../assets/images/cars/civic1.jpg",
      "../assets/images/cars/civic2.jpg",
      "../assets/images/cars/civic3.jpg"
    ],
    features: ["Sport mode", "Touchscreen display"],
    description: "Sporty design with fun driving experience."
  },

  {
    id: 7,
    brand: "Ford",
    model: "Focus",
    type: "Hatchback",
    year: 2019,
    price: 950000,
    mileage: 110000,
    fuel: "Diesel",
    transmission: "Manual",
    color: "Silver",
    horsepower: 120,
    engineSize: 1499,
    drive: "FWD",
    consumption: 4.8,
    doors: 5,
    seats: 5,
    inspection: true,
    images: [
      "../assets/images/cars/focus1.jpg",
      "../assets/images/cars/focus2.jpg",
      "../ assets/images/cars/focus3.jpg"
    ],
    features: ["Cruise control", "Bluetooth"],
    description: "Compact hatchback with low running cost."
  },

  {
    id: 8,
    brand: "Tesla",
    model: "Model 3",
    type: "Sedan",
    year: 2023,
    price: 3100000,
    mileage: 5000,
    fuel: "Electric",
    transmission: "Automatic",
    color: "Black",
    horsepower: 283,
    engineSize: 0,
    drive: "RWD",
    consumption: 0,
    doors: 4,
    seats: 5,
    inspection: true,
    images: [
      "../assets/images/cars/tesla1.jpg",
      "../assets/images/cars/tesla2.jpg",
      "../assets/images/cars/tesla3.jpg"
    ],
    features: ["Autopilot", "Touchscreen", "Electric drive"],
    description: "Fully electric vehicle with advanced tech."
  },

  {
    id: 9,
    brand: "Nissan",
    model: "Qashqai",
    type: "SUV",
    year: 2024,
    price: 1650000,
    mileage: 3000,
    fuel: "Petrol",
    transmission: "Automatic",
    color: "Green",
    horsepower: 140,
    engineSize: 1332,
    drive: "FWD",
    consumption: 6.1,
    doors: 5,
    seats: 5,
    inspection: true,
    images: [
      "../assets/images/cars/qashqai1.jpg",
      "../assets/images/cars/qashqai2.jpg",
      "../assets/images/cars/qashqai3.jpg"
    ],
    features: ["360 camera", "Blind spot assist"],
    description: "Popular SUV with comfortable driving."
  }
];